### ISSUE TITLE
Publish to gh-pages using Travis fails

### ISSUE THREAD

**Issue by sole** [devtools-html/docs#1]
Example of failed build: https://travis-ci.org/devtools-html/docs/builds/244937876

**Comment by sole** [comment]
(I have disabled travis builds in the meantime so as to not to get 404s)

**Comment by bwinton** [comment]
So, I've [published](https://github.com/bwinton/photon/blob/master/deploy.sh) [a few](https://github.com/bwinton/podcasts/blob/master/deploy.sh) [things](https://github.com/bwinton/icons/blob/master/deploy.sh) to gh-pages with Travis, and here's the general structure of what I end up doing:

My `.travis.yml` only checks out master, and [calls a shell script](https://github.com/bwinton/photon/blob/master/.travis.yml#L8) to do the rest.
That shell script [gets a clone of gh-pages](https://github.com/bwinton/photon/blob/master/deploy.sh#L8) into a `dist` directory, [runs the build](https://github.com/bwinton/photon/blob/master/deploy.sh#L14) to put the new contents into the `dist` directory, and then [commits the results](https://github.com/bwinton/photon/blob/master/deploy.sh#L23).
(The running of the build can be whatever you want, as long as it ends up populating `dist`.  Here's [what I use](https://github.com/bwinton/photon/blob/master/package.json#L7).)

The one other thing you need to do is add a secret `GH_TOKEN` environment variable to your Travis build that contains one of your [GitHub personal access tokens](https://github.com/settings/tokens).

If any of this is unclear, please feel free to ping me on email/slack/irc/this issue, and I'll try to explain it more or answer any questions you may have!

**Comment by sole** [comment]
Thanks @bwinton - this gave me a few pointers. I have documented the solution in the [README](https://github.com/devtools-html/docs/blob/master/README.md), and it seems to be chugging along nicely now!
