### ISSUE TITLE
Documentation made available as downloadable file

### ISSUE THREAD

**Issue by Ricky-Tigg** [devtools-html/docs#12]
Enhancement request: Official [documentation](https://developer.mozilla.org/en-US/docs/Tools) made available as downloadable file such as EPUB or PDF.

**Comment by captainbrosset** [comment]
There are 2 types of documentations in devtools:

* user docs, found on MDN, the one you linked to
* contributor docs, found on docs.firefox-dev.tools

This github repo is only concerned with the latter. Making the user docs downloadable sounds good, but here isn't the place to ask for this enhancement. I think https://github.com/mdn/kuma might be a better place for this.
