### ISSUE TITLE
Content is cut-off on mobile

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/docs#13]
I was talking to Aarushi Vij on Slack and she mentioned the following:

> if I open the docs in my phone, the content cuts out, neither there's a scroll bar to see the part that is cut.

Aarushi also provided the following screenshots:

![Screenshot_20200203-220547](https://user-images.githubusercontent.com/1152698/73725404-978e3080-472d-11ea-8c1d-81f177aac878.jpg)
![Screenshot_20200203-220556](https://user-images.githubusercontent.com/1152698/73725411-9ceb7b00-472d-11ea-999c-a2486079289f.jpg)

**Comment by gudianirudha** [comment]
**add this part of code:**

body {
    -ms-overflow-style: scrollbar;
}
