### ISSUE TITLE
Remove book.json file

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/docs#14]
Should we remove the `book.json` if it has no effect?
Added in https://github.com/firefox-devtools/docs/commit/05bf08c8bce2f9c0d263a977554635cff2620eb2

Honza

**Comment by janodvarko** [comment]
@captainbrosset WDYT?

**Comment by captainbrosset** [comment]
Yes we should. This was a first attempt at fixing the issue we had with the gitbook build failure, but this was not the right place to have this file. Let's remove it.
